repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [ts, javascript]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 07fd005
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
